### ISSUE TITLE
MEAN book Question- Getting Users by ID

### ISSUE THREAD

**Issue by drelbert** [amejiarosario/ama#9]
Hi Adrian, 
Really enjoying your MEAN book.  Very well written and organized.  

I am having some troubles with the “Reading a single user document using findOne()” section.  I was able to get the the list of users, but after modifying the users.server.controller and users.server.routes . js files the browser returns a "cannot GET /users/[id]" message.  Thinking it was an error in my typing, I simply copied and pasted the example code but now get an "Error: Cannot find module '../build/Release/bson'" message in the terminal when I start the node server.  

I'm working on a Mac running 10.12.2 Sierra and my package.json file matches exactly the dependencies outlined in the book.  

Thank you in advance.
Cheers,
Dan

**Comment by amejiarosario** [comment]
Hi @drelbert,

Thanks for the interest in the book! What chapter are you on? You can find what your code should looks like on each chapter by picking the corresponding branch from: https://github.com/amejiarosario/meanshop#getting-a-chapters-code.

Also if you are getting errors that some module is not installed, did you tried `npm install`? That should install all the missing dependencies.

Let me know if that helps,

Thanks again for your interest and sorry for the delay

**Comment by drelbert** [comment]
Thanks Adrian,
I'll give this a try.  

Dan
